github.com:
    users:
        curiousstitches:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: curiousstitches
